[app:main]
use = egg:multitwitch

pyramid.reload_templates = true
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en
static.cache_max_age = 0
twitch.client_id =
twitch.client_secret =
twitch.redirect_uri = http://localhost:6543/auth/twitch/callback
twitch.session_db = data/twitch_sessions.sqlite3
twitch.secure_cookies = false
pyramid.includes =
    pyramid_debugtoolbar
    pyramid_tm

[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 6543

# Begin logging configuration

[loggers]
keys = root, multitwitch

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_multitwitch]
level = DEBUG
handlers =
qualname = multitwitch

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s

# End logging configuration
